controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


github.login:
    path: '/github/login'
    controller: App\Controller\GitHubLoginController::login

github.check:
    path: '/github/check'
    controller: App\Controller\GitHubLoginController::check

